package settings

import (
	"errors"
	"os"
	"path/filepath"
	"testing"
)

func TestSessionTimeout(t *testing.T) {
	dir := t.TempDir()
	s := New(dir)
	if n, err := s.SessionTimeout(); err != nil || n != 300 {
		t.Fatalf("default: %d %v", n, err)
	}
	if err := s.SetSessionTimeout(450); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(filepath.Join(dir, "rega.conf"))
	if string(data) != "# rega.conf\n# This file is generated by cp_security.cgi\nSessionTimeout=450\n" {
		t.Fatalf("%q", data)
	}
	if n, _ := s.SessionTimeout(); n != 450 {
		t.Fatal(n)
	}
	for _, bad := range []int{179, 601, 0} {
		if err := s.SetSessionTimeout(bad); !errors.Is(err, ErrInvalid) {
			t.Errorf("%d: %v", bad, err)
		}
	}
}
