package settings

import (
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// The WebUI's session timeout: ReGa reads it from /etc/config/rega.conf on
// its start, cp_security.cgi action_set_session_timeout writes it
const (
	regaConf              = "rega.conf"
	DefaultSessionTimeout = 300
	MinSessionTimeout     = 180
	MaxSessionTimeout     = 600
)

// SessionTimeout reads the timeout in seconds; without a setting the
// default of 300 s (dialogSettingsSecurityHintSessionTimeout2)
func (s *Service) SessionTimeout() (int, error) {
	data, err := os.ReadFile(s.path(regaConf))
	if errors.Is(err, os.ErrNotExist) {
		return DefaultSessionTimeout, nil
	}
	if err != nil {
		return 0, err
	}
	for _, line := range strings.Split(string(data), "\n") {
		key, value, ok := strings.Cut(line, "=")
		if ok && strings.TrimSpace(key) == "SessionTimeout" {
			if n, err := strconv.Atoi(strings.TrimSpace(value)); err == nil {
				return n, nil
			}
		}
	}
	return DefaultSessionTimeout, nil
}

// SetSessionTimeout writes rega.conf as cp_security.cgi does; ReGa takes
// it on the next start of the CCU
func (s *Service) SetSessionTimeout(seconds int) error {
	if seconds < MinSessionTimeout || seconds > MaxSessionTimeout {
		return fmt.Errorf("%w: the session timeout must be %d to %d seconds", ErrInvalid, MinSessionTimeout, MaxSessionTimeout)
	}
	return writeFile(s.path(regaConf), fmt.Sprintf("# rega.conf\n# This file is generated by cp_security.cgi\nSessionTimeout=%d\n", seconds))
}
