#!/bin/sh

# Definieren Sie den Pfad zu Ihrem Addon-Verzeichnis
ADDON_DIR="/usr/local/addons/homematic-mui5"
# RC DIR
RC_DIR=/usr/local/etc/config/rc.d

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# Erstellen Sie das Addon-Verzeichnis, falls es noch nicht existiert
mkdir -p $ADDON_DIR

# dist ordner nach addon kopieren
cp -af dist/* $ADDON_DIR

# Setzen Sie die Berechtigungen
chmod -R 755 $ADDON_DIR

# Kopieren Sie die Addon-Konfigurationsdatei in das richtige Verzeichnis
cp -f homematic-mui5.config /usr/local/etc/config/addons/

# Installieren Sie das RC-Skript
cp -f rc_script $RC_DIR/homematic-mui5
chmod +x $RC_DIR/homematic-mui5

sync

# Leiten Sie die Ausgabe in eine Datei um
exec > /usr/local/etc/config/addons/install-h-mui5.log 2>&1

exit 0