#!/bin/sh

ADDON_DIR=/usr/local/addons/mui
RC_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config/addons

mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

mkdir -p $ADDON_DIR && chmod -R 755 $ADDON_DIR

cp -af dist/* $ADDON_DIR

cp -f mui.config $CONFIG_DIR/mui.config

cp -f rc.d/mui $RC_DIR/mui
chmod +x $RC_DIR/mui

sync

exit 0